### ISSUE TITLE
Callback URI doesn't support other reverse proxy ports

### ISSUE THREAD

**Issue by timwis** [ueberauth/ueberauth#103]
I'm using phoenix to build an API and building a Vue.js app alongside it to serve as the client. I'm running the Vue.js app as a separate process to take advantage of webpack-dev-servers goodies, and reverse proxying my phoenix API through it: `localhost:8080/api/*` and `/auth/*` get routed to my phoenix server (`localhost:4000/api/`). This works fine, except the request to `/auth/auth0` initiates a login with a callback uri using the underlying phoenix server's port. Reading through #14 and the [related source code](https://github.com/ueberauth/ueberauth/blob/master/lib/ueberauth/strategies/helpers.ex#L167) I can see that ueberauth supports the `x-forwarded-proto` header for similar situations like nginx reverse proxying to provide SSL, but what should I do in this situation? It seems similar enough to the SSL situation -- plus the fact that I imagine sometimes you want to serve SSL on a port other than 443 -- that I wonder if the library should support `x-forwarded-port`? If so, I'm happy to submit a PR for it, just thought I'd get your thoughts first.

**Comment by yordis** [comment]
@hassox ^

**Comment by jamesvl** [comment]
I ran into this recently and am proposing an MR shortly for a fix.
