### ISSUE TITLE
error plug in umbrella project (phantom behavior)

### ISSUE THREAD

**Issue by otsybulsky** [ueberauth/ueberauth#105]
I try use ueberauth in standart umbrella application, but i have this error. Help, please!
![Screen Shot 2019-07-16 at 6 02 06 PM](https://user-images.githubusercontent.com/34866613/61306052-94b10a00-a7f4-11e9-8106-02a486b59916.png)

**Comment by yordis** [comment]
Did you add Ueberauth dependency to your project?

How?

**Comment by otsybulsky** [comment]
my deps list
```
defp deps do
    [
      {:phoenix, "~> 1.3.4"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      {:gettext, "~> 0.11"},
      {:itemli, in_umbrella: true},
      {:plug_cowboy, "~> 1.0"},
      {:ueberauth, "~> 0.6"},
      {:ueberauth_google, "~> 0.8"},
      {:absinthe, "~> 1.4"},
      {:absinthe_phoenix, "~> 1.4.0"},
      {:absinthe_plug, "~> 1.4"},
      {:absinthe_relay, "~> 1.4.0-rc or ~> 1.4"},
      {:cors_plug, "~> 2.0"}
    ]
  end

def application do
    [
      mod: {Itemli.Web.Application, []},
      extra_applications: [:logger, :runtime_tools, :ueberauth, :ueberauth_google]
    ]
end
```

**Comment by OvermindDL1** [comment]
You mention umbrella, that's the `deps` of that specific umbrella subproject?  Because you should not be getting that error if so.

**Comment by otsybulsky** [comment]
Yes, it's web subproject of umbrella, `defmodule Itemli.Web.Mixfile`, and error in 
```
defmodule Itemli.Web.AuthController do
  use Itemli.Web, :controller
  plug(Ueberauth)
end
``` 
I test this in standart phx.new project, there error not found.

**Comment by otsybulsky** [comment]
I made new phx.new --umbrella for test `plug Ueberauth`, error is active.

**Comment by OvermindDL1** [comment]
That still implies the dependencies aren't fetched somehow.  Can you post a minimal reproduceable project onto github that we can clone to try it out?

**Comment by otsybulsky** [comment]
Error disappeared magically. All I did was turn off the computer yesterday and turned on today. I suspect that the reason was somewhere in the interaction vscode + vscode extensions + OS Mojave + external ssd system disc. It looks weird, but everything works. Thank you very much for your help.

**Comment by OvermindDL1** [comment]
Ah, there have been oddities with the language server someone made for elixir projects, were you getting the error 'through' that rather than the terminal?

**Comment by otsybulsky** [comment]
This error occurred while writing the code, before compilation.

**Comment by OvermindDL1** [comment]
Yep!  That's the language server then.  It's a bit buggy in that way, always test via the mix commands on the terminal.  :-)

**Comment by otsybulsky** [comment]
ok, thank you
