### ISSUE TITLE
Allow dynamic providers

### ISSUE THREAD

**Issue by mildred** [ueberauth/ueberauth#106]
I have a use case where we need to authenticate using OAuth apps that are not fixed once for all in the configuration, but with dynamic OAuth apps. Basically, the secret OAuth keys are in database and not in environment or configuration.

Apparently, Ueberauth is not designed to handle this case.

I found out that it should be possible to use `Ueberauth.Strategy.run_{request,callback}` directly, but those functions are not documented and some values are passed through a private `ueberauth_request_options`.

Would it be possible to document a public API that would allow dynamic providers?

Thank you

**Comment by mildred** [comment]
This should probably be an issue for the various providers so they can take their options from the `ueberauth_request_options` private and not the global config too.

**Comment by yordis** [comment]
Closed in favor of https://github.com/ueberauth/ueberauth/issues/90

**Comment by mdillavou** [comment]
I also am running into this issue where I need to dynamically configure a strategy based on the user for a multi-tenant system. While the run_request and run_callback is really helpful for dynamically picking strategies, it appears that most of the strategies still expect their oauth configuration (client id/client secret) to be in the environment.

Is there a recommended method that strategies should start using to be more dynamic, rather than requiring us to configure something like:

**Comment by nicolasblanco** [comment]
@mdillavou : I had the same issue with building a multi-tenants with the Google Strategy : I wanted to use multiple OAuth keys.
But by reading the source of the strategy I found that it was reading the OAuth2 clients options also from the private `ueberauth_request_options`.

https://github.com/ueberauth/ueberauth_google/blob/master/lib/ueberauth/strategy/google.ex#L163

So I was able to simply pass `client_id` and `client_secret` in the call to `Ueberauth.run_request` with

```
{Ueberauth.Strategy.Google,
                  [
                    client_id: "...",
                    client_secret: "..."
                  ]}
```

I think it would be easier to just fork the strategy that is not reading the client options from `ueberauth_request_options` and make something similar to the Google Strategy, the PR should be then be accepted I guess 👍 .

**Comment by mdillavou** [comment]
That is interesting! I think it would be great if ueberauth came up with a recommendation for all strategies so we'd have consistency. Ideally, all strategies would resolve the configuration options in the following order:

1. Get the parameters from the conn's `:ueberauth_request_options`
2. Get the parameters from the config based on the current `:otp_app`
3. Get the parameters from the config for the default `:ueberauth` app

That way we keep compatibility and it gives those of us that need more options the flexibility. 

One thing I have noticed is that every strategy goes about this differently. I think ueberauth should include some helper functions to resolving these configuration options to make sure strategies are consistent.
