### ISSUE TITLE
Reverse Proxy configuration

### ISSUE THREAD

**Issue by justinbkay** [ueberauth/ueberauth#115]
I have Nginx running as a reverse proxy for my Phoenix app.  I have it *almost* working correctly with the authentication, but the callback is coming through as http instead of https.

I click the login link, select my account, and I get redirected to http://mydomain.com/auth/google/callback? instead of https://...

I'm sure this is some type of configuration error on my part, but I'm not sure if it is an Nginx configuration problem or Phoenix.  Any help would be much appreciated.

nginx.conf

<pre>
location @proxy {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
                proxy_pass http://domain_tracker;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }
</pre>

**Comment by Hanspagh** [comment]
Could you post your phoenix config aswell?

**Comment by justinbkay** [comment]
Ok, it was the variable $http_x_forwarded_proto, not being set correctly in the nginx config.  I tested it by changing out the variable name with a string and it started working as expected.

**Comment by justinbkay** [comment]
Here's the Nginx config for posterity:

<pre>
  map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
  }

  map $http_x_forwarded_proto $real_scheme {
    default $http_x_forwarded_proto;
    ''      $scheme;
  }

  location @proxy {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $real_scheme;
    proxy_set_header Host $http_host;
    proxy_set_header Connection ""; # For keepalive
    proxy_http_version 1.1;         # For keepalive
    proxy_intercept_errors on;
    proxy_redirect off;
    proxy_pass http://domain_tracker;
  }
</pre>

This allows socket connections, and the redirects work properly for logging in with Ueberauth with SSL enabled and Nginx as the reverse proxy.
