### ISSUE TITLE
CaseClauseError at GET /auth/google/callback

### ISSUE THREAD

**Issue by chriscreber** [ueberauth/ueberauth#120]
I'm not sure if I need to show all of my configurations, because I seem to be getting an error from google's side. I can get to the login page, but once I login I receive the error shown in the images. It a case clause issue that occur before google even passes control.
<img width="1149" alt="Screen Shot 2020-05-21 at 1 52 58 PM" src="https://user-images.githubusercontent.com/35268038/82605301-8e08c700-9b6a-11ea-9e2b-3ee9b5486e0f.png">
<img width="1792" alt="Screen Shot 2020-05-21 at 1 46 42 PM" src="https://user-images.githubusercontent.com/35268038/82605316-94973e80-9b6a-11ea-819f-d418f55096a3.png">
<img width="1792" alt="Screen Shot 2020-05-21 at 1 46 54 PM" src="https://user-images.githubusercontent.com/35268038/82605324-97922f00-9b6a-11ea-9fcd-d5dd3658aa5d.png">

**Comment by chriscreber** [comment]
<img width="923" alt="Screen Shot 2020-05-21 at 1 55 35 PM" src="https://user-images.githubusercontent.com/35268038/82605492-dd4ef780-9b6a-11ea-985b-8af6c330f949.png">
<img width="895" alt="Screen Shot 2020-05-21 at 1 55 52 PM" src="https://user-images.githubusercontent.com/35268038/82605507-e049e800-9b6a-11ea-99b8-d8c9d385d2ab.png">

**Comment by andreaseriksson** [comment]
I just reinstalled my computer and got this error. Can it be Elixir related?

**Comment by andreaseriksson** [comment]
Its an issue with hackney and OTP 23. 
I added this and it works for now:
```elixir
{:hackney, git: "https://github.com/benoitc/hackney.git", branch: "master", override: true}
```

**Comment by Hanspagh** [comment]
Seems to be fixed for now. Closing
