### ISSUE TITLE
incorrect route prefix construction

### ISSUE THREAD

**Issue by starkeepers** [ueberauth/ueberauth#146]
When running (a phoenix app) under a path with several segments, such `example.com/a/b/`, and keeping the standard routes for ueberauth, ie `example.com/a/b/auth/:provider`, the private function `Ueberauth.run/2` miscalculates the path, creating  `example.com/ab/auth/:provider` instead. This is because of:

`to_request_path  = Path.join(["/", conn.script_name, options.request_path])`

where `conn.script_name` is `["a", "b"]`. The documentation of Path.join explicitly mentions that this will result in "a" and "b" being mashed together. A pull request is on its way.

**Comment by yordis** [comment]
closed by #166
