### ISSUE TITLE
Allow strategies to set SameSite value of state param cookie

### ISSUE THREAD

**Issue by Awlexus** [ueberauth/ueberauth#148]
I'm currently trying to update ueberauth_apple to use ueberauth 0.7 and add csrf protection, but I'm running into a problem, because Apple uses a javascript when performing the POST request to the callback_url. 

Would it be possible to allow strategies to define the SameSite value? In the meantime, I will set ignores_csrf_attack for now and add my own cookie

**Comment by yordis** [comment]
PR welcome if you have something in mind
