### ISSUE TITLE
Can't mock out Ueberauth.Strategy in 0.8.0

### ISSUE THREAD

**Issue by connorjacobsen** [ueberauth/ueberauth#150]
In `0.6.3` we used to be able to mock out the `Ueberauth.Strategy` (with `Mox` or otherwise), but in `0.8.0` we cannot because there is no way to mock out the `default_options/0` function.

Are there any other recommended testing strategies that don't require mocking out the `Ueberauth.Strategy` module?

**Comment by yordis** [comment]
Would you mind expanding the issues you are facing?

**Comment by connorjacobsen** [comment]
Specifically, I am using some of the other packages from ueberauth (such as `ueberauth_google`, etc) in my application and I would like to be able to test the login flow (which uses these packages). In `0.6.3` I was able to use `Mox` and mock out the `Ueberauth.Strategy` module. However, in `0.8.0`, the `default_options/0` gets squirted into any modules that `use Ueberauth.Strategy`, but it is defined within the `using` macro so I cannot get at it to mock it out. Does that make sense?

**Comment by yordis** [comment]
Right, I understand what is happening but not why it is happening, I haven't used Mox myself, so I am not sure what the precise issue is in order to help you.

Maybe share some basic setup, error log, or something.

**Comment by connorjacobsen** [comment]
Ah, sorry. Mox effectively works by using a stubbed implementation of an elixir `behaviour` and you can intercept the functions when they are exercised by your tests. You _cannot_ mock out functions that are not part of the mocked behaviour.

So I can intercept and handle methods like `handle_request!` and `handle_callback!` without issue. But since `default_options/0` is the a public method in `Ueberauth.Strategy` that is not also defined as a callback _and_ it is ultimately called by `run_request`, `Mox` is blowing up (rightly) because the behaviour doesn't have a callback for `default_options`.

I am happy to put together a little example app with the issue if that is helpful. If the conclusion here requires any code changes, I am happy to implement them or help out as useful.

I see that the library test has a very simple implementation that it uses for tests. Is it suggested to do something like that instead of trying to mock out the Strategy module callbacks? It's also very possible the way I'm approaching things is just dumb and wasn't obviously dumb until now.

**Comment by yordis** [comment]
For the most part, I am actually curious to know what are you trying to test, since it wouldn't be clear to me why you would test ueberauth itself, but rather the result of it.

In case you want to do the integration test, then I would swap the implementation to some "in-memory" or some simple implementation of an actual strategy rather than mocking.

So I am not sure, trying to put some example repo that help us to test and fix the potential problem, and/or come up with some "better" solution to the problem

**Comment by revoltaxz** [comment]
I'm with same problem here! I was updated my deps `{:ueberauth_google ~> 0.10.0}` and `{:ueberauth ~> 0.7.0}`, after that my tests failed and return undefined error (error below):

```
   ** (UndefinedFunctionError) function ObramaxWeb.Ueberauth.ClientMock.default_options/0 is undefined or private
     code: conn = get(conn, auth_session_path(conn, :callback, :google))
     stacktrace:
       ObramaxWeb.Ueberauth.ClientMock.default_options()
       (ueberauth 0.7.0) lib/ueberauth/strategy.ex:383: Ueberauth.Strategy.get_ignores_csrf_attack_option/1
       (ueberauth 0.7.0) lib/ueberauth/strategy.ex:326: Ueberauth.Strategy.run_callback/2
```

So

**Comment by yordis** [comment]
Hey peeps, do you mind testing https://github.com/ueberauth/ueberauth/pull/154 and sharing some 1+?

**Comment by revoltaxz** [comment]
I was tested and my tests failed again, because returns a `csrf_token error` (error below). Is necessary add another config?

```
%Plug.Conn{
  adapter: {Plug.Adapters.Test.Conn, :...},
  assigns: %{
    ueberauth_failure: %Ueberauth.Failure{
      errors: [
        %Ueberauth.Failure.Error{
          message: "Cross-Site Request Forgery attack",
          message_key: :csrf_attack
        }
      ],
      provider: :google,
      strategy: ObramaxWeb.Ueberauth.ClientMock
    }
  },
```

**Comment by yordis** [comment]
Well, this is expected if you didn't pass back the state, not sure what you are doing in your test case

**Comment by fuelen** [comment]
The issue is still present.

I've tried v0.9.0 and cannot mock the module with Mox, as function `auth/1` is unknown.
`auth/1` is called only if `handle_callback!` assigns `ueberauth_failure` or `ueberauth_auth` structs.

I think it is better not to generate `auth/1` function and define it in another module with the following signature `auth(Plug.Conn.t(), module())`.
WDYT? @yordis

**Comment by yordis** [comment]
@fuelen that sounds correct, do you mind creating a PR, with some testing reflecting the issue?
