### ISSUE TITLE
OAuth2 needs new maintainers

### ISSUE THREAD

**Issue by scrogson** [ueberauth/ueberauth#152]
Hey folks! I haven't been able to give OAuth2 the TLC it needs and wanted to checkin to see if this might be a project we'd like to rollup under the Ueberauth org?

If so...I can transfer the repo here and give hex access to whomever is responsible for cutting new releases.

Thoughts?

**Comment by Hanspagh** [comment]
I think it should like something we can take of.

**Comment by doomspork** [comment]
Sounds good to me @scrogson 👍

**Comment by yordis** [comment]
I can take care of the release part of it, just let me know once it is done.

**Comment by scrogson** [comment]
Repo has been transferred: https://github.com/ueberauth/oauth2
And transferred ownership on hex to the `ueberauth` org.

Thanks y'all, I know this library will be in good hands. ❤️
