### ISSUE TITLE
How can run Ueberauth plug directly?

### ISSUE THREAD

**Issue by shahryarjb** [ueberauth/ueberauth#156]
Hi, Dear maintainer and Contributor, 
I have a controller function named login which uses protocol to be modular, hence I need to run Ueberauth plug directly, but I do not know how

Please see my code:
```elixir
defmodule MishkaSocial.Auth.Router do
  defimpl MishkaSocial.AuthProtocol, for: MishkaSocial.Auth.Strategy do
    use Phoenix.Controller, namespace: MishkeSocialWeb
    import Plug.Conn
    plug Ueberauth

    @spec login(MishkaSocial.Auth.Strategy.t()) :: any
    def login(%MishkaSocial.Auth.Strategy{conn: conn, endpoint: "html", id: social}) do
      # TODO: redirect to the social network to get token and basic information based on social:id
      # TODO: get basic information based on a struct to recognize
      # TODO: check this email of user exists in the databse or not
      # TODO: if doesnt exist, create a new user and login user with creating token and session
      # TODO: if exists, so login user and create token and session
      # TODO: it should be noted, check the identeties of user and create this for user and make it unique with social:id
      request(conn, %{"provider" => social})
    end

    def request(conn, _params) do
      render(conn, "request.html", callback_url: Ueberauth.Strategy.Helpers.callback_url(conn))
    end
  end
end
```

I try to call `Ueberauth.call(conn, routes)` but I do not know what is the routes to prepare its requirement. So I can not redirect to google or the other providers.
```elixir
# my config
config :ueberauth, Ueberauth,
base_path: "/auth/login",
```

## My controller for more clarity

```elixir
  def login(conn, %{"email" => "shahryar.tbiz@gmail.com", "password" => "something_as_password"}) do
    render(conn, "login.html")
  end

  def login(conn, %{"params" => entry}) do
    # developer or client should send a map as params key and this map must includ struct which is your module name
    # for example Elixir.MishkaSocial.Auth.Strategy, it should be noted, this module have to have struct under itself
    convert_controller_to_protocol(conn, entry)
  end
```

> By the way, I can not my function to be redirected even `Ueberauth.call(conn, Ueberauth.init([]))`

Thank you in advance for taking the time to respond to my issue, and I hope to hear from you.
Sincerely yours,
Shahryar Tavakkoli

**Comment by yordis** [comment]
The solution would be applicable to any `Plug`, so I am not sure what your issue is precise since you already did what I had in mind.

1. Call the `init` function https://github.com/ueberauth/ueberauth/blob/7ebc0aeeb17d0953bdc53a01018307fb03e0b189/lib/ueberauth.ex#L272
2. Call the `call` function https://github.com/ueberauth/ueberauth/blob/7ebc0aeeb17d0953bdc53a01018307fb03e0b189/lib/ueberauth.ex#L283

Sorry I couldn't help much here.

I am gonna close the issue since it seems that it is not a problem with the package but something related to your code.

**Comment by shahryarjb** [comment]
Hi Dear @yordis, I did not mean that there is a problem with your library.
For this problem, we should change `conn` like this:

```elixir
Map.merge(conn, %{request_path: "/auth/login/google", method: "GET"})
    |> Ueberauth.call(Ueberauth.init([]))
    |> halt()
```

**Comment by yordis** [comment]
@shahryarjb use https://github.com/ueberauth/ueberauth/discussions/categories/q-a to ask questions instead. So we keep the Issues related to feature work and bugs.
