### ISSUE TITLE
writing a custom strategy

### ISSUE THREAD

**Issue by sobolevn** [ueberauth/ueberauth#17]
I'm working on a project with the need for server-side social-auth. Your library seems pretty good, but there's a strategy missing. I would like to use https://vk.com/ OAuth (the biggest SN in Russia), but it is not in the list. 

What do you think, is it worth implementing? Do you have any guidelines how to contribute whole new strategy? 

Thanks!

**Comment by doomspork** [comment]
@sobolevn you can take a look at the strategies we currently have for an example of how to create a new one.  Whether or not it's worth implementing is up to you :grinning:  

I've been adding strategies as I have a need for them, that way they don't go unused and get stale.

**Comment by sobolevn** [comment]
Hi! I have implemented a strategy for the vk. Check it out: https://github.com/sobolevn/ueberauth_vk

**Comment by doomspork** [comment]
That's awesome @sobolevn! 

@hassox & @scrogson what do you think about adding a README section or Wiki page with a list of strategies?

**Comment by sobolevn** [comment]
I am also wondering how to test it? In development I have used `ueberauth_example` app with modifications to test it.

**Comment by doomspork** [comment]
That's a good question @sobolevn, that's what I've been doing too.  We've been bouncing around ideas about how to best test strategies.  Suggestions are welcome!

**Comment by doomspork** [comment]
@sobolevn I've added a list of strategies to our Wiki, feel free to add yours: https://github.com/ueberauth/ueberauth/wiki/List-of-Strategies

In the mean time, join us on Slack in #ueberauth, and help us come up with a clever way to test strategies.
