### ISSUE TITLE
Gracefully handle unknown providers

### ISSUE THREAD

**Issue by fuelen** [ueberauth/ueberauth#173]
### Steps to Reproduce

1. Setup Ueberauth according to README
2. go to /auth/unknown_provider

### Expected Result

404 error

### Actual Result

500 error

**Comment by mathieuprog** [comment]
For anyone who might need this, kinda obvious but in the meanwhile this can be done:
```elixir
  plug :check_if_known_provider when action in [:request]
  plug Ueberauth

  @known_providers ~w(google)

  def check_if_known_provider(conn, _params) do
    provider = Map.fetch!(conn.params, "provider")

    if provider in @known_providers do
      conn
    else
      conn
      |> send_resp(400, "")
      |> halt()
    end
  end
```

**Comment by yordis** [comment]
I couldn't replicate the issue: https://github.com/ueberauth/ueberauth/pull/191

**Comment by fuelen** [comment]
@yordis I think that's because all routes in the test router are defined explicitly, while we use this
```elixir
scope "/auth", MyApp do
  pipe_through :browser

  get "/:provider", AuthController, :request
  get "/:provider/callback", AuthController, :callback
end
```
*copied from `ueberauth_google` README*

**Comment by Hajto** [comment]
https://github.com/ueberauth/ueberauth/pull/193
Here is my proposed solution to the problem. It sets the error that can be handled in the the user callback and presets the status.

The question is:
 - Do we remove the status set?
 - Should we halt the connection?

This boils down to two solutions:
 - Should we leave this error to be handled by the user?
 - Should it always return 404?

Imo the visual way of handling this will depend on the application so I think I should remove the status and let the user handle the error however the library user wants.

**Comment by fuelen** [comment]
I'd suggest raising an exception which implements `Plug.Exception` protocol, where the status is specified as 404.
In this case application will render a developer-defined error page.

**Comment by Hajto** [comment]
That is a lovely idea, I will try to incorporate it.

**Comment by Hajto** [comment]
![image](https://github.com/ueberauth/ueberauth/assets/8336429/9d9e7b6c-79ae-41bc-b71e-3cb89de14be0)

**Comment by Hajto** [comment]
I did push the proposal. Once it gets traction and gets approved I will write proper tests for this scenario.

**Comment by fuelen** [comment]
@yordis sorry, but commit with the test you've merged doesn't solve the issue. It tests the following line
https://github.com/ueberauth/ueberauth/blob/7b1aabab66abea02cebf051bb2137dbc36c82283/test/support/spec_router.ex#L44
and not the code I've mentioned above:
```elixir
  get "/:provider", AuthController, :request
```

**Comment by yordis** [comment]
@fuelen I understand that it doesn't solve your problem, but that test failed with the changes that broke some people production code (which is the reason why I merged).

Another word, I am not proving that your situation is resolve.
