### ISSUE TITLE
minor: mix package versions are out of date

### ISSUE THREAD

**Issue by jamesvl** [ueberauth/ueberauth#177]
### Steps to Reproduce

Run `mix hex.outdated`

### Expected Result

Nothing it out of date.

### Actual Result

```
Dependency   Current  Latest  Status
credo        1.5.5    1.6.7   Update possible
dialyxir     1.1.0    1.2.0   Update possible
ex_doc       0.23.0   0.29.1  Update possible
excoveralls  0.14.0   0.15.3  Update possible
inch_ex      2.0.0    2.0.0   Up-to-date
plug         1.11.0   1.14.0  Update possible
```

These are all minor (should be non-breaking changes).

To view the diffs in each available update, visit:
https://hex.pm/l/kmMV8

**Comment by yordis** [comment]
Do you mind creating a PR? Otherwise, I should have some time next week.
