### ISSUE TITLE
Add a redirect_uri function so that the redirect_uri is configurable

### ISSUE THREAD

**Issue by aef-** [ueberauth/ueberauth#18]
Hi there! Currently I'm using only the callback functionality of ueberauth (specifically Facebook and Google). My client grabs the access code and then sends it to my API in order to retrieve the token. On dev I'm running my API and client on separate ports, so to support how most ueberauth's implement handle_callback by setting the redirect_uri as so: `opts = [redirect_uri: callback_url(conn)]`, I need a reverse proxy.

Adding a a helper function redirect_uri that grabs either the uri from the config or callback_url for oauth implementations to use would be really helpful for scenarios like this.

What do you think?

**Comment by doomspork** [comment]
@aef- PRs are welcome for new functionality 👍

**Comment by nicooga** [comment]
I don't wheter this is related, but I'm also working with a single page application and an elixir API.
I'm using https://github.com/sahat/satellizer to fire the popups on the single page, then `POST`ing with code to the API. The result is an ueberauth error `redirect_uri_mismatch`.

~~~elixir
pry(6)> params
%{"clientId" => "...",
  "code" => "4/vLOSfRQi-OK6B...",
  "provider" => "google", "redirectUri" => "http://localhost:3333",
  "state" => "....."}
pry(7)> fails
%Ueberauth.Failure{errors: [%Ueberauth.Failure.Error{message: nil,
   message_key: "redirect_uri_mismatch"}], provider: :google,
 strategy: Ueberauth.Strategy.Google}
~~~

I'm not sure how to continue, I'm pretty sure I've configured well the allowed redirect uris on google console.

**Comment by nicooga** [comment]
Indeed, made a fork to implement this functionality and that worked for me.

~~~elixir
config :ueberauth, Ueberauth,
  providers: [
    google: {Ueberauth.Strategy.Google, [
      callback_methods: ["POST"],
      callback_path: "/api/auth/google/callback",
      callback_url: "http://localhost:3333"
    ]}
  ]
~~~

Making a PR ASAP.

**Comment by doomspork** [comment]
This has been merged into master.  I'll release a new version later this evening, ideally with #28 included.
