### ISSUE TITLE
Incomplete docs to configure pipeline and check that user is authenticated

### ISSUE THREAD

**Issue by jakelacey2012** [ueberauth/ueberauth#188]
### Problem Statement

To the fresh reader ueberauth clearly describes how you would integrate with a provider, however what it does not do is describe and help the reader how they would securely lock down a route using a plug - the documentation is lacking in this area. 

How would I do this could this be added to the documetnation? Also the readme assumes that the user would know how to setup a auth_controller?

**Comment by yordis** [comment]
> How would I do this could this be added to the documetnation? Also the readme assumes that the user would know how to setup a auth_controller?

Follow https://diataxis.fr/ framework to improve the docs.

**Comment by Hajto** [comment]
Can I get more information on the topic?

**Comment by Hajto** [comment]
What does `locking down a route` mean in this context?
