### ISSUE TITLE
Latest release breaks existing paths

### ISSUE THREAD

**Issue by wkirschbaum** [ueberauth/ueberauth#194]
### Steps to Reproduce

On the user session controller we have a new action with a login screen, as well as the callback actions.,

Visiting `http://localhost:4000/users/log_in` crashes the page with the following error: 

```
Ueberauth.NoProviderError at GET /users/log_in

Provider users/log_in was not found
```

### Expected Result

The existing routes should not crash, even if it renders on the same controller as the callback action, or the changelog should specify this breaking change. 

### Actual Result

It crashes the existing routes.

**Comment by yordis** [comment]
I would like to add a test case to replicate the issue, but also,

It is tricky the existing situation about #193 and https://github.com/ueberauth/ueberauth/issues/173

It comes down to "what should Ueberauth expect people to do?", I am open to suggestions here.

**Comment by yordis** [comment]
https://github.com/ueberauth/ueberauth/pull/191 I should merge that one before accepting the PR, it was passing before!

😢 My apologies folks, you live you learn!

**Comment by nathanalderson** [comment]
I think you need to publish a version with the rollback in addition to retiring the release. Retiring the release doesn't seem to stop `mix deps` from pulling it in if there's no newer version.

**Comment by yordis** [comment]
uuufff I thought I forgot about it, but it is marked as "retired" thou

![Screenshot 2024-01-02 at 11 54 41 AM](https://github.com/ueberauth/ueberauth/assets/4237280/58a8b627-fd7d-495a-805d-ecdd48c9940c)
