### ISSUE TITLE
Extra field on `%Info{}` struct

### ISSUE THREAD

**Issue by sobolevn** [ueberauth/ueberauth#21]
Should we consider adding an extra field to the `%Info{}` struct? Like we already have `other_params` on `token`. 

It is handy to store extra information from the social provides, such as: age, gender, birthdays, hometown, and so on.

Any drawbacks I am missing?

**Comment by Trevoke** [comment]
I think the ability to extend the permissions for retrieved info might be good, but it's also beyond the direct scope of Ueberauth, whose responsibility is only to authenticate. Authentication has nothing to do with a person's age.

So, maybe an extension / add-on for Ueberauth?

**Comment by sobolevn** [comment]
Anyway it is defined already: https://github.com/ueberauth/ueberauth/blob/master/lib/ueberauth/auth/info.ex

**Comment by hassox** [comment]
As @doomspork pointed out to me the other day we can use the `Auth.Extra` struct to store arbitrary data that is not handled by the other struct. https://github.com/ueberauth/ueberauth/blob/master/lib/ueberauth/auth/extra.ex
