### ISSUE TITLE
I would like to create a Steam strategy using OpenID

### ISSUE THREAD

**Issue by Gacnt** [ueberauth/ueberauth#24]
Is there any sort of starter kit for making a strategy, or do I need to basically copy pasta somebody elses strategy and change what needs to be changed, also does Guardian support OpenID as well?

**Comment by doomspork** [comment]
@Gacnt we don't currently have a kit for making strategies, copy+pasta is your best bet.  That said, if you've got suggestions for a kit I'd be open to hear them 😀 

As for OpenID, I'm not sure.  Ueberauth is flexible and can work with most two-phase authentications schemes (OAuth, OAuth 2.0, Auth0).
