### ISSUE TITLE
trailing slashes affect oauth redirection

### ISSUE THREAD

**Issue by jasonrig** [ueberauth/ueberauth#27]
Hi,
There currently seems to be an issue where the presence of a trailing slash will fallback to rendering the request template (e.g. [this template](https://github.com/ueberauth/ueberauth_example/blob/master/web/templates/auth/request.html.eex) in the example code) rather than redirecting to the OAuth service.

https://ueberauth-example.herokuapp.com/auth/google works
https://ueberauth-example.herokuapp.com/auth/google/ does not work

Any idea how to make both the example with and without the trailing slash work?

**Comment by doomspork** [comment]
This is resolved, thank you @jasonrig 👍
