### ISSUE TITLE
How to submit a new Ueberauth Plugin?

### ISSUE THREAD

**Issue by zberkom** [ueberauth/ueberauth#30]
Hi there,

I've just written an Ueberauth plugin for Dwolla authentication and I'm just wondering what the protocol is to get it included under the Ueberauth github organization. 

I will agree to maintain the project overtime, so it won't be something you guys have to take care of.

Just let me know what next steps I should take. 

Thanks!

**Comment by doomspork** [comment]
Hi @zberkom, for now we're only including strategies and projects under the Ueberauth org that are created and maintained by the team.  

Feel free to include your strategy with the rest of them in the Wiki here: https://github.com/ueberauth/ueberauth/wiki/List-of-Strategies

**Comment by zberkom** [comment]
@doomspork Great, thanks. I'll do that.
