### ISSUE TITLE
Allow Config Option for Custom URLs

### ISSUE THREAD

**Issue by nikkomiu** [ueberauth/ueberauth#34]
Currently there is an option for adding custom paths but in certain cases there is a need to be able to use a custom URL instead of a custom path.

**Comment by doomspork** [comment]
@hassox / @scrogson do you have any objections to supporting this new feature?  

The particular case for which this came up is SSL termination with nginx, Ueberauth creates the callback with `http://` when `https://` is needed.

**Comment by hassox** [comment]
@doomspork is this the `X-Forwarded-Proto` header issue? Wondering if we need this still. @nikkomiu?

**Comment by nikkomiu** [comment]
I don't think this is needed anymore. If the X-Forwarded-Proto is set I believe it uses the correct URL.

**Comment by yordis** [comment]
@nikkomiu is this related to #65 Could we close this one and move the conversation to #65 then? @ueberauth/core

**Comment by yordis** [comment]
@nikkomiu it seems to be related to #65

I will close this one but feel free to open the issue if you think they are not the same.
