### ISSUE TITLE
Best practice to deal with refresh tokens

### ISSUE THREAD

**Issue by nambrot** [ueberauth/ueberauth#37]
This might be related to https://github.com/ueberauth/ueberauth_google/issues/16, but I was wondering what the best practice around dealing with offline access/refresh tokens are?

**Comment by hassox** [comment]
I think for refresh tokens the application should schedule and query for the refresh. I think this is out of scope for ueberauth itself. @doomspork @scrogson thoughts?

**Comment by scrogson** [comment]
Agreed. Ueberauth is for obtaining tokens through the oauth2 authorization code flow.
