### ISSUE TITLE
Consider using a normal plug, with less code generation

### ISSUE THREAD

**Issue by chrismccord** [ueberauth/ueberauth#4]
Ideally, you wouldn't need to break from the regular plug api, so instead of this:
    
    Ueberauth.plug "/auth"

You could do

    plug Ueberauth, strategy: MyStrategy

or 
    
    plug Mystrategy

As it is today, calling `Ueberauth.plug` generates an external module from the caller, which is a sign we can probably find a better way, such as having the user define an explicit module that `use UeberAuth.Strategy`, then plug that. Thoughts?

**Comment by scrogson** [comment]
:+1:

**Comment by hassox** [comment]
The Ueberauth.Strategy has a different role than what this module provides, this module is constructing the route matching.

I've seen quite a few pubs that provide a macro to setup routes. I'll catch up with @scrogson and see what options we can rustle up

**Comment by chrismccord** [comment]
In either case, the generated module should be one that the user explicitly defines, then they plug that in the router

**Comment by chrismccord** [comment]
For example, it seems the entire code generation could be a normal `UeberAuth` plug module, which accepts options from the plug, i.e.:

```elixir
defmodule UeberAuth do
  def init(opts) do
    opts = Application.get_env(:ueberauth, Ueberauth)
    parts = Enum.map(opts[:providers], fn { name, { strategy, options } } ->
      request_path = Dict.get(options, :request_path, Path.join(["/", base_path, to_string(name)]))
      callback_path = Dict.get(options, :callback_path, Path.join(["/", base_path, to_string(name), "callback"]))
      methods = Dict.get(options, :callback_methods, ["GET"]) |> Enum.map(&(String.upcase(to_string(&1))))

      %{
        strategy_name: name,
        strategy: strategy,
        callback_path: callback_path,
        request_path: request_path,
        callback_methods: methods,
        options: options
      }
  end

  def call(conn, opts), do: run!(conn, opts[:base_path], opts[:callback_path], opts)

  defp run!(%Conn{path_info: [base_path | _]}, base_path, _callback_path, opts) do
    conn
    |> Plug.Conn.put_private(:ueberauth_request_options, opts)
    |> Strategy.run_request(opts[:strategy])
  end

  defp run!(%Plug.Conn{path_info: [cb_path | _]} = conn, _base, cb_path, opts) do
    if conn.method in opts[:callback_methods] do
      conn
      |> Plug.Conn.put_private(:ueberauth_request_options, opts)
      |> Strategy.run_callback(opts[:strategy])
    else
      conn
    end
  end
  defp run!(conn, _), do: conn # if we don't match anything just fall through
end
```

**Comment by scrogson** [comment]
Thanks for the feedback @chrismccord.
