### ISSUE TITLE
Allow to add extra params to callback_url 

### ISSUE THREAD

**Issue by radzserg** [ueberauth/ueberauth#40]
Would be good to have ability to pass extra params to callback_url. For example users can login and register, can register for different roles - user, advertiser, whoever.  

If I could build callback_url from current conn params, e.g.  /auth/facebook?param1=val1&param2=val2
I could use these params in callback_phase to define what to do after successful sign in. 

Most of strategies rely on callback_url function from Helpers module 
`|> Keyword.put(:redirect_uri, callback_url(conn, [no params here]))`
FB Instagram VK Twitter 

So I guess it's possible to add whitelist of params to config for callback_url. And then fetch this params from conn and automatically add to callback_url.

Maybe there's another approach for this. Appreciate any feedback.

**Comment by dotdotdotpaul** [comment]
I was trying to figure this out as a way to handle redirecting the user when they come back from the auth -- I figured I could pass the referer [sic] as an option to the callback URL and then when they come back, after success, I could send them back "where they came from".

It seems like this use case (redirect to where the login originated) would be a pretty frequently desired result -- am I missing something in the current implementation that already does this?

**Comment by terencechow** [comment]
@radzserg @dotdotdotpaul 

How are you guys handling this currently? I believe I have a similar use case. I have users which have subscriptions and each subscription can have many authorizations. On an auth callback, I have no idea which subscription has made the the authorization and cannot connect them.

**Comment by dotdotdotpaul** [comment]
My current hack is that my login URL is now auth/login/:provider, and that shoves the referer into the session, then redirects to auth/:provider to let Ueberauth work as usual.  Then I added to the callback function code that checks the session for the referer, removes it from the session and then redirects (defaulting to "home" if not found).  Works fine, if your user is using cookies -- but I figure if someone isn't using cookies, the login isn't going to work particularly well anyway.

**Comment by doomspork** [comment]
@radzserg I haven't personally had a need for this functionality but there is quite a bit of interest, would you be interested in submitting a pull request for review?

**Comment by radzserg** [comment]
@doomspork I will. Give me 2 weeks. Completely busy this week.

**Comment by radzserg** [comment]
https://github.com/ueberauth/ueberauth/pull/45
