### ISSUE TITLE
I would like to create a passwordless strategy

### ISSUE THREAD

**Issue by obsidienne** [ueberauth/ueberauth#41]
Hi,

Can you give me guidances to create a strategy following this principal: [passwordless auth](https://www.sitepoint.com/passwordless-authentication-works/)
[Medium.com](https://medium.com/) is an actual website using this auth pincipal.

Is it possible at least to create this strategy ?

Thanks

**Comment by doomspork** [comment]
@obsidienne I do think this is something that could be accomplished with Ueberauth.  I'd need to consider the approach a bit more before I could provide guidance.

Any thoughts @hassox?

**Comment by kelostrada** [comment]
I didn't read too much into the article, but I guess you want to make it work by sending an email with proper link to make user able to login? I don't think it should be really difficult to implement this tbh.

**Comment by deini** [comment]
@obsidienne Did you created the strategy? I would like this strategy too, if you haven't I can give it a shot when I get some time.

**Comment by kumekay** [comment]
@deini Did you work on such strategy?

**Comment by deini** [comment]
@kumekay I have not, I'm sorry. I ended up writing a custom solution.
