### ISSUE TITLE
Creating Custom Callback URIs for Mobile Apps

### ISSUE THREAD

**Issue by bawolf** [ueberauth/ueberauth#49]
Is there a way to create Redirect URIs for Mobile Apps?

I would like to return a callback like ` myapp://callback#token=<token>` so that the phone knows to call the app and open it ala something like [this](https://www.oauth.com/oauth2-servers/redirect-uris/redirect-uris-native-apps/)

I didn't see an optional parameter for this?

**Comment by doomspork** [comment]
@bawolf I've never done something like this, could you elaborate on the requirements a bit more?

**Comment by scrogson** [comment]
@bawolf that would be for an authorization server (like Facebook or Google) to pass the access token back to the mobile client. This isn't something that you would do with Ueberauth.

Ueberauth is acting as a client to auth provider.

I hope that answers your question.
