### ISSUE TITLE
connect_timeout in facebook login

### ISSUE THREAD

**Issue by aliabbas-2012** [ueberauth/ueberauth#52]
OAuth2.Error at GET /auth/facebook/callback
:connect_timeout
I tested on different machine and browsers its still happening

**Comment by Hajto** [comment]
More information would be useful.

**Comment by doomspork** [comment]
@aliabbas-2012 as @Hajto mentioned, more information would be helpful.  Do you have an example project that we could use to replicate this behavior?  I would double check it isn't a firewall issue.

Are you able to make API requests directly, outside of Ueberauth?

**Comment by Hajto** [comment]
@aliabbas-2012 If you provide more info and maybe example that will help reproduce the error I will try to fix it.

**Comment by aliabbas-2012** [comment]
Should I send you the zip of my project ?

**Comment by Hajto** [comment]
@aliabbas-2012 I think link to git repo would be better.

**Comment by aliabbas-2012** [comment]
https://github.com/aliabbas-2012/phoenixBlog

**Comment by aliabbas-2012** [comment]
it is in 1.2 series

**Comment by aliabbas-2012** [comment]
branch name is facebook_login

**Comment by doomspork** [comment]
Thanks @aliabbas-2012!  I've just returned from holiday, I'll take a peek this week 👍

**Comment by yordis** [comment]
@aliabbas-2012 do you still issue?

Even when we have a demo project, we will appreciate some step to reproduce and explain what you did already.

Feel free to open the issue if the issue persist but we will need information about it since could be issues with your Facebook credentials 🤷‍♂️
