### ISSUE TITLE
Decoupling OAuth2 provider endpoint details from Überauth

### ISSUE THREAD

**Issue by chrislaskey** [ueberauth/ueberauth#59]
Hey all, thanks for the great work on üeberauth! Had an idea and wanted to run it by you all, especially @doomspork @hassox and @scrogson.

### Background

I've been building an application that uses Elixir as a GraphQL back-end. It uses different OAuth2 providers for user authentication using a mix of Authorization Code and Implicit flows.

Choosing Facebook as a first implementation, I read through the `ueberauth/ueberauth_facebook` code to see how y'all do it. In my case, I can't call the functions directly since I'm not using the rest of überauth to manage the user login.

Which got me to thinking - what if the provider specific OAuth2 functions had their own package? Then it could be used on its own (my use case) or as an integration point to `ueberauth/ueberauth_facebook`.

### As a stand-alone package

So I spun up [`chrislaskey/oauth2_facebook`](https://github.com/chrislaskey/oauth2_facebook) to explore it. Fundamentally, it just pulls all the endpoint specific code (e.g. building the `/me?` path) out of `Ueberauth.Strategy.Facebook` - decoupling the endpoint details from the überauth details.

One potential advantage is the endpoint specific code now lives in its own package. Using a separate library like this would lighten the maintenance required on an integration like `ueberauth_facebook` since you'd only have to manage the data translation instead of also managing the provider endpoint details.

It'd also be a general purpose library for users needing lower-level calls, like I do.

### Feedback

As for the code itself, there's still some more work better organize the code - I've overloaded the Strategy file to contain both the generic OAuth `get_token!` calls and specific endpoint calls like `get_user`. Would need to talk with Sonny about the right way to organize it.

At any rate, the important pieces are there - it works, there's some test coverage. Enough that you should be able to see the shape of it. Thoughts and feedback appreciated. Cheers!

**Comment by scrogson** [comment]
Hey @chrislaskey!

Thanks for creating this issue. This is definitely something that has come up a lot and we are meaning to come up with a solution.

What you propose is definitely one way to help solve this issue (and a good one). The main thing that I hesitate with on that approach is having too many dependencies to maintain.

Having each `ueberauth` package maintain its own OAuth2 abstraction code allows for easier maintenance on our part. Also, it's not much code either.

I think the plan (at this time) is to improve the API so that the OAuth2 functions are made public and can be called on their own outside of the normal flow (as discussed in https://github.com/ueberauth/ueberauth/issues/20).

**Comment by chrislaskey** [comment]
Hey Sonny! Thanks for the great reply.

> I think the plan (at this time) is to improve the API so that the OAuth2 functions are made public and can be called on their own outside of the normal flow (as discussed in #20).

Makes sense, but mind if I press on that a bit? I think with the expertise and skills on your team you'd crush it. There's no doubt you _could_ do it, but I'm wondering if you _should_ do it?

It feels like a slippery slope towards y'all being maintainers for a variety of OAuth2 related workflows, many of which falling outside the scope of Überauth.

I originally started writing a pull request against `ueberauth/ueberauth_facebook` but it quickly started to feel like what I was adding didn't really belong there. These kinds of feature requests feel lower-level than the project itself. Which is why it felt better to break it out into its own package that becomes a dependency instead of part of überauth itself.

If it lives on its own, then it becomes much easier and more natural to add a token introspection endpoint. Or handle the peculiarities of a specific provider - like Facebook requiring an additional call to get a [long-lived token](https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension). Or implementing a non-Authorization Code flow. All the while überauth can become a consumer of only the parts it cares about.

Not to mention there'd be a lot less thought over where to draw the line, what additional features to support. A lot less weekend PRs and comments to reply to after work too. 😸 

At any rate, huge respect for you and the überauth team. Thanks for hearing me out, will continue to support y'all whichever direction you decide to take!

**Comment by chrislaskey** [comment]
Closing this issue out. For completeness I went ahead and released an [oauth2_facebook](https://hex.pm/packages/oauth2_facebook) hex package. Cheers!
