### ISSUE TITLE
Any helpers to ueberauth callbacks in a Phoenix application?

### ISSUE THREAD

**Issue by anildigital** [ueberauth/ueberauth#62]
Hi,

I am working on a Phoenix application where I am using Ueberauth Slack.
I wanted to write controller tests for callbacks

``` 
def callback(%{assigns: %{ueberauth_failure: _fails}} = conn, _params) do.
```
...
```
def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
```

Any helpers to set assigns properly while testing? 

Thanks!

**Comment by doomspork** [comment]
Sorry @anildigital we don't have a testing harness yet.  The best solution I've found so far is to rely on `bypass`.  If you have any suggestions for how we could make testing easier we're all ears!

**Comment by Papipo** [comment]
Where can I see an example of that? Thanks!
