### ISSUE TITLE
Gitlab Strategy Integration

### ISSUE THREAD

**Issue by mtchavez** [ueberauth/ueberauth#63]
Hey,

Not sure if this is the best place for this but I made a [Gitlab OAuth2 Strategy][gitlab-repo] and tested it out using the [Example App][example-app]. How do new strategies normally get consumed by the Üeberauth github org? I wouldn't mind transfering ownership and becoming a collaborator to help maintain the strategy.

If there is a better place to discuss please let me know. Thanks.

[example-app]: https://github.com/ueberauth/ueberauth_example
[gitlab-repo]: https://github.com/mtchavez/ueberauth_gitlab

**Comment by doomspork** [comment]
Howdy @mtchavez!  We don't _currently_ accept other strategies into the org but we're currently looking at ways to do so as well as enable maintainers to continue to provide support 👍
