### ISSUE TITLE
URL Resolution - Scheme, Host, Port

### ISSUE THREAD

**Issue by cgorshing** [ueberauth/ueberauth#65]
I'm working through deploying my first Phoenix app and ran into issues with the URL's used for the different strategies. This specific app has nginx sitting in front of it (I resolved the issues by forwarding across x-forwarded-proto and x-forwarded-for).

I didn't want to use the ueberauth configuration of overriding the callback url because I'm using quite a few strategies and didn't want to have lots of duplication around. I had added configuration to `prod.exs` as: `  url: [scheme: "https", host: "sitename.com", port: 443]`, 

But the different ueberauth strategies don't seem to use those settings.

It looks like Ueberauth uses:

    defp full_url(conn, path, opts) do
      scheme = conn
      |> forwarded_proto
      |> coalesce(conn.scheme)
      |> normalize_scheme

      %URI{
        host: conn.host,
        port: normalize_port(scheme, conn.port),
        path: path,
        query: encode_query(opts),
        scheme: to_string(scheme),
      }
      |> to_string
    end

Whereas Phoenix uses the following (from  https://github.com/phoenixframework/phoenix/blob/10b6c1e8df915e82a4040f14f94afc1aed8ab47a/lib/phoenix/endpoint/supervisor.ex#L235-L255):

    defp build_url(endpoint, url) do
      build_url(endpoint.config(:https), endpoint.config(:http), url)
    end

    defp build_url(https, http, url) do
      {scheme, port} =
        cond do
          https ->
            {"https", https[:port]}
          http ->
            {"http", http[:port]}
          true ->
            {"http", 80}
        end

      scheme = url[:scheme] || scheme
      host   = host_to_binary(url[:host] || "localhost")
      port   = port_to_integer(url[:port] || port)

      %URI{scheme: scheme, port: port, host: host}
    end

I'm curious to know the decisions around using something different than Phoenix. I believe Uberauth could be used outside of Phoenix and this might be the reason, but I would favor this consistency. Having called this out in the README would have been great too (maybe it is already in the docs someplace and I didn't read enough).

**Comment by doomspork** [comment]
@cgorshing we're just pulling the values straight off the connection.  If you're using `https`, we'll use `https`.  In your case, it sounds like you're using SSL termination?  If that's the case, I think the issue is your Phoenix configuration since we'll just copy settings over from the connection struct.

Comparing what Phoenix does as a framework to what Ueberauth does as a Plug is going to lead to a lot of confusion 👍

**Comment by cgorshing** [comment]
"Comparing what Phoenix does as a framework to what Ueberauth does as a Plug is going to lead to a lot of confusion" - I looked more closely at the deps of ueberauth and plug, and I agree that they shouldn't be tied to Phoenix.

"I think the issue is your Phoenix configuration" - My configuration is correct (just confirmed it by using an obviously wrong setup and saw they results). But Phoenix uses the :url config and ueberauth does not (which makes sense).

I guess my point is how Phoenix generates URL's is different from Ueberauth. I would also think that some other framework would generate the URL's in a different way as well.

I think it makes sense to have an override option for how the URL is generated. A function that can be called to get at the "base_url" of the site.

If you still disagree, then no worries and go ahead and close this issue.

**Comment by jabberfest** [comment]
@doomspork , @cgorshing brings up a good point. Here is an example use case where the current implementation causes problems:

- Phoenix running on port:4000 with http
- Nginx running on port 443 with TLS and a reverse proxy to port:4000

If I set the following in my production config
```
config :demo, Demo.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "www.chat-me-now.com", scheme: "https"],
  static_url: [scheme: "https", host: "foobar.cloudfront.net", port: 443]
```

Then all my phoenix asset path helpers will have the correct "https" prefix. The redirect URI generated by Helpers.callback_url(conn) will always show "http" because thats the scheme set on the "conn".

Since nginx is what maintains the https connection between  browser client and server the redirect URI will never have https.

In Phoenix all routes from route helpers are not generated from the "conn" struct itself, they are generated from the options passed into ":url". ":static_url" is used for static assets.

**Comment by jabberfest** [comment]
So it looks like the fix  is to set the "X-Forwarded-Proto" header. Maybe the fix is to clarify the docs. I didn't realize this until I was digging in the source code.

In nginx:
```
proxy_set_header X-Forwarded-Proto $scheme;
```

In: ueberauth/lib/ueberauth/strategies/helpers.ex the scheme is set to the X-Forwarded-Proto header if it's set.

```elixir
  defp full_url(conn, path, opts) do
    scheme = conn
    |> forwarded_proto
    |> coalesce(conn.scheme)
    |> normalize_scheme
```

```elixir
  defp forwarded_proto(conn) do
    conn
    |> Plug.Conn.get_req_header("x-forwarded-proto")
    |> List.first
  end
```

**Comment by cgorshing** [comment]
My use case was the same and solved it the same way. I do agree we don't want these tied together, but it would be good to have the same logic (for now since Phoenix tends to be the main way to use these). This is still in the back of my mind and I may submit a PR in the future if I can get to it.

**Comment by honkycat** [comment]
My two cents: It's very strange that Uberauth is making assumptions about my protocol.

SSL termination is not an uncommon use case, and having to set up an nginx server and set a header is a lot of work compared to a simple configuration change in Uberauth.

In my opinion, the protocol should be configurable to always return `https` without having to rely on the side-effect of a header.

**Comment by yordis** [comment]
Since is a common practice to put a server like Ngnix in front of the Phoenix app, I believe that it is a good idea to configure the scheme.

**Comment by honkycat** [comment]
As a SRE developer I'm going to have to disagree with you @yordis . There are many examples where this is not realistic of feasible, and adding an nginx server to an existing stack isn't as easy as snapping your fingers, whereas providing a config would be much simpler. Would people be open to a pull request implementing this feature?

### The problem with the nginx solution:

As an application developer, I now have to go to my ops team and ask them to set up configurations, tooling, and monitoring for an entire new nginx server.

As an ops team member I have to add an additional nginx server to my tooling. This means I must:

- Update all of my existing environments to new include an Nginx server in order for Uberauth to respond with the proper protocol

- Update all existing provisioning tooling to include the new nginx server

- Write the nginx server's configuration which includes implementing a reverse proxy and adding a header 

- I have to add the nginx server to my continuous deployment services, which means writing automated tooling, testing, and deployment

- Nginx health checks have some idiosyncratic behaviour, so now I must write health checks and monitoring for my new nginx server, which again, only exists so I can have Uberauth respond with the proper protocol.

- Keep the new nginx server in my mind during debugging / triage process, ensuring that it is not causing issues.

**Comment by yordis** [comment]
@honkycat  by all means, create a PR with your suggested implementation.

**Comment by primitive-type** [comment]
I'm very confused. Does `callback_url` work as it's described in the following issues?

https://github.com/ueberauth/ueberauth/issues/18
https://github.com/schwarz/ueberauth_discord/issues/3

If it does, wouldn't it solve both this issue and also https://github.com/ueberauth/ueberauth/issues/34 by allowing for the hardcoding of `https://` into the `callback_url` directly? Am I missing something?

**Comment by ramyma** [comment]
I'm having the same problem; I'm accessing the Phoenix app on port 80 through nginx on port 443, and I want to make the callback the URL use the HTTPS scheme.
I've added `proxy_set_header X-Forwarded-Proto $scheme;` as @jabberfest suggested to my nginx config but to no avail.
I also tried adding `callback_scheme: "https"` to the provider config but as mentioned here in the thread it's linked somehow to the Phoenix app scheme.

Did anyone find a solution to this problem?

**Comment by ramyma** [comment]
Actually adding `proxy_set_header X-Forwarded-Proto $scheme;` in the location block in the nginx config did the trick. I had some other error in my code that got me mixed up!

So if anyone is looking scratching their heads, here's how you should have your nginx config set:
```
location /YOUR_PATH {
                proxy_pass http://127.0.0.1:8888;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_cache_bypass $http_upgrade;
        }
```

Replace `8888` with your desired port.

I hope this helps.

**Comment by Hanspagh** [comment]
Having `X-Forwarded-Proto` when using a reverse proxy is quite common, and I don't see a reason for adding a config for this current. Fell free to reopen if this continues to be an issue.
