### ISSUE TITLE
Separate ueberauth config for different app under umbrella project

### ISSUE THREAD

**Issue by bluzky** [ueberauth/ueberauth#78]
Hi! I'm working on an umbrella project, I have 2 apps, one for admin and one for user.
I want both admin and user can login using facebook account. 
- `admin -----auth---> facebook  app for admin`
- `user -----auth----> facebook app for user`

**this is config for admin app**
```elixir
config :ueberauth, Ueberauth,
  providers: [
    facebook: {Ueberauth.Strategy.Facebook, []}
  ]

config :ueberauth, Ueberauth.Strategy.Facebook.OAuth,
  client_id: System.get_env("ADMIN_FB_ID"),
  client_secret: System.get_env("ADMIN_FB_SECRET")
```

**this is config for user app**
```elixir
config :ueberauth, Ueberauth,
  providers: [
    facebook: {Ueberauth.Strategy.Facebook, []}
  ]

config :ueberauth, Ueberauth.Strategy.Facebook.OAuth,
  client_id: System.get_env("FB_ID"),
  client_secret: System.get_env("FB_SECRET")
```
Admin account cannot login using facebook because it use configuration for user app.
How can I separate configuration for admin and user app?
Thank you

**Comment by scrogson** [comment]
@bluzky unfortunately, what you wish to do is not currently possible. Sorry about that.

Configuration in Elixir is a hot topic at the moment and the configuration story for Ueberauth really needs to be revisited. This will likely require a new major version. There is currently nothing on the road map for this, but the core team and I will discuss it soon.

**Comment by yordis** [comment]
Moved to #90
