### ISSUE TITLE
Cryptic build error if config isn't set.

### ISSUE THREAD

**Issue by janderland** [ueberauth/ueberauth#86]
This is not a bug but rather an idea for an improvement. If the Ueberauth config isn't set for your current environment, then during compilation a cryptic build error arises:

```
Compiling 24 files (.ex)

== Compilation error in file lib/onward_web/controllers/auth_controller.ex ==
** (FunctionClauseError) no function clause matching in Keyword.pop/3

    The following arguments were given to Keyword.pop/3:

        # 1
        nil

        # 2
        :base_path

        # 3
        "/auth"

    Attempted function clauses (showing 1 out of 1):

        def pop(keywords, key, default) when is_list(keywords)

    (elixir) lib/keyword.ex:964: Keyword.pop/3
    lib/ueberauth.ex:177: Ueberauth.init/1
    (plug) lib/plug/builder.ex:302: Plug.Builder.init_module_plug/4
    (plug) lib/plug/builder.ex:286: anonymous fn/5 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:284: Plug.Builder.compile/3
    (phoenix) expanding macro: Phoenix.Controller.Pipeline.__before_compile__/1
    lib/onward_web/controllers/auth_controller.ex:1: OnwardWeb.AuthController (module)
```

This could be prevented by adding a check for the presence of the configuration right before [this line](https://github.com/ueberauth/ueberauth/blob/master/lib/ueberauth.ex#L175). If the configuration isn't found, then an exception could be thrown or we could have a pattern match fail so that the user sees the configuration isn't present.

I could do this, but before I do I wanted to run the idea by you in this issue.

**Comment by doomspork** [comment]
A PR to improve this would be much appreciated @janderland 👍

**Comment by janderland** [comment]
Added a pull request for this [here](https://github.com/ueberauth/ueberauth/pull/91).
