### ISSUE TITLE
Configurable json serializer

### ISSUE THREAD

**Issue by snewcomer** [ueberauth/ueberauth#87]
@yordis @doomspork 👋 Following up on a previous discussion of allowing users to configure their json encoder/decoder.  Some apps may be using `Jason` instead of `Poison` for example.

For OAuth2 (a dep of many other ueberauth libraries), it looks like `Poison` is the default, but they allow you to configure it via application config `serializers` based on a mime-type [here](https://github.com/scrogson/oauth2/pull/52/files#diff-04c6e90faac2675aa89e2176d2eec7d8R30).  

However, as of now, this would require setting, say `Jason` as the serializer like so:

```
# only ueberauth_twitter for now (correct me if I am wrong though) as it is still using oauth1.1
config :ueberauth, json_library: Jason

# all other ueberauth wrapper libraries I believe, which use oauth2
config :oauth2, 
  serializers: %{
    "application/vnd.api+json" => Jason,
    "application/json" => Jason
  }
```

There is an outstanding PR to allow registration of serializers via `OAuth2.register_serializer/2` instead of application config.  This would be very useful.
 https://github.com/scrogson/oauth2/pull/92

For now, it seems we could move forward with `json_library` config to allow `ueberauth_twitter` to use `Jason` (or whatever other serializer) if it so desired and note in the README that other libraries (google, facebook, github) can configure accordingly (although I admit this is a bit deceiving).  Once/if the related PR above is merged, we could then do the work to make this integration simpler.  Lmk what you think or if there is a better way than what I outlined above!

Previous discussion https://github.com/ueberauth/ueberauth_twitter/issues/26

**Comment by yordis** [comment]
Still relevant https://github.com/ueberauth/ueberauth_twitter/issues/26#issuecomment-449599246

The first step is to get the strategies to use Ueberauth JSON library (understanding the trade-off which I would like to hear your feedbacks)
