### ISSUE TITLE
Improve configuration

### ISSUE THREAD

**Issue by yordis** [ueberauth/ueberauth#90]
As a user, I should be able to configure the strategies at runtime.

Umbrella applications where we could have multiple Web layers we should be able to have different configurations for Ueberauth based on the apps.

Users want to load the configuration from soft of a database. The workflow should allow you to configure the strategies at runtime when the workflow is initialized.

## Proposal

The Ueberauth API should allow the user to initialize the workflow with the desired configuration.

## Notes

Ueberauth shouldn't care how the configuration is load, the initialization of the workflows should allow us to pass the config.

Workflow initialized manually could take the configuration in the function call. 

Workflow initialized throw Plug has two use cases.

1. Umbrella app, since you could have multiple apps the Plug would take multiple instances of Ueberauth configurations.

2. The configuration is loaded based on some information from the connection.

Related to #78 #51 please read the threads for more details about it.

**Comment by doomspork** [comment]
@yordis would you say this has been satisfied with #94?

**Comment by yordis** [comment]
@doomspork we need to be able to initialize all the Ueberauth workflows without having to rely on anything from `Config` module.

Since configurations could change based on the runtime we can't read the config at compilation (unless you read from the environment, but that is not the best solution)

@hassox did some work about this which I will continue on it, let me get back to you today.

**Comment by alexparker** [comment]
Yea not loving the tight coupling assumption of env variables being the source, would love to have this, or help get this out asap. Thanks!

**Comment by doomspork** [comment]
@alexparker we welcome any PRs to improve Ueberauth and the strategies, please do help 😁

**Comment by mildred** [comment]
I have a draft PR here: https://github.com/ueberauth/ueberauth/pull/107 (I need to test it, but it's based on code that works elsewhere)

**Comment by yordis** [comment]
@mildred 🚀 🚀 🚀 🚀 🚀

**Comment by Hanspagh** [comment]
Closed by #107
