### ISSUE TITLE
Invalid plug dependency - unable to use with phoenix 1.4.1

### ISSUE THREAD

**Issue by mspanc** [ueberauth/ueberauth#99]
The plug dependency is defined as `~> 1.5.0`. It is a wrong pattern to use such notation when referring to the library with the semantic versioning. It should be `~> 1.5` instead, as we can rely on the fact that unless major number change, the newer versions should be backwards compatible. Current approach is too strict.

Current approach disallows using ueberauth with phoenix 1.4.1.

```
$ mix deps.get
Resolving Hex dependencies...

Failed to use "plug" (version 1.7.2) because
  phoenix (version 1.4.1) requires ~> 1.7
  phoenix_ecto (version 4.0.0) requires ~> 1.0
  phoenix_html (version 2.13.1) requires ~> 1.5
  plug_cowboy (version 2.0.1) requires ~> 1.7
  ueberauth (version 0.6.0) requires ~> 1.5.0
  mix.lock specifies 1.7.2
```

**Comment by mspanc** [comment]
@yordis wow, that was quick. Any chance for 0.6.1 release that has proper dependencies?

**Comment by yordis** [comment]
@mspanc https://github.com/ueberauth/ueberauth/pull/101

**Comment by doomspork** [comment]
I'll cut a release here shortly @mspanc 😀

**Comment by yordis** [comment]
@doomspork LEL it happened at the same time 😄  check the PR I need some CR please 💜
